tasks:
  - init: ./gradlew build
  - name: Install JDK
    # before:
    # yes command is for answering 'setting this java version as default'
    init: yes | sdk install java 17.0.3-ms
    # command:
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-spring-initializr
    - Pivotal.vscode-spring-boot
    - vscjava.vscode-spring-boot-dashboard
