spring:
  redis:
    database: 0
    host: redis-10071.c240.us-east-1-3.ec2.cloud.redislabs.com
    port: 10071
    password: AjZfAdfzTWrDEaaTIACyTNshxfdcTHPZ
id-generator:
  datacenter-id: 1
  time-bits: 40
  datacenter-bits: 2
  worker-bits: 9
  sequence-bits: 12
  start-timestamp-str: "2022-07-15 00:00:00"
worker-manager:
  timeout: 1800 # unit: second
  heartbeat-rate: 30 # unit: second
