package com.swetroye.idgenerator;

public interface IdGenerator {
    /**
     * 
     * @return an id generated by Snowflake algorithm
     */
    public long getId();

    /**
     * Parsed the id into elements.
     * eg. timestamp & datacenterId & workerId & sequence
     * 
     * @param id
     * @return Parsed info
     */
    public String parseId(long id);

}
